#29 fix xsd e templates per validazione
geosolutions-it/iso19139.rndt pull request #122
Opened 2020-11-04 11:17 UTC by taba90

- fix cardinalità su xsd.
- fix templates service: srv:extent -> gmd:extent

2020-11-04 14:04 UTC, etj requested changes

2020-11-04 14:04 UTC, etj commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-armonized-service.xml
> +      <gmd:extent>
`srv:extent` is ok for services

2020-11-04 14:04 UTC, etj commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-interoperable-service.xml
> +      <gmd:extent>
`srv:extent` is ok for services

2020-11-04 14:04 UTC, etj commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-invocable-service.xml
> +      <gmd:extent>
`srv:extent` is ok for services

2020-11-04 14:04 UTC, etj commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-network-service.xml
> +      <gmd:extent>
`srv:extent` is ok for services

2020-11-04 14:04 UTC, etj commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-service.xml
> +      <gmd:extent>
`srv:extent` is ok for services

2020-11-05 14:27 UTC, taba90 commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-armonized-service.xml
> +      <gmd:extent>
fixed

2020-11-05 14:27 UTC, taba90 commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-interoperable-service.xml
> +      <gmd:extent>
fixed

2020-11-05 14:27 UTC, taba90 commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-invocable-service.xml
> +      <gmd:extent>
fixed

2020-11-05 14:27 UTC, taba90 commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-network-service.xml
> +      <gmd:extent>
fixed

2020-11-05 14:27 UTC, taba90 commented on src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-service.xml
> +      <gmd:extent>
fixed

2020-11-06 15:23 UTC, etj commented
Superseded by #125

2020-11-06 15:23 UTC, closed without merging