#188 Id Risorsa
geosolutions-it/iso19139.rndt pull request #201
Opened 2020-12-07 16:59 UTC by taba90

Campo identificatore da RS_Identifier a MD_Identifier

2020-12-10 17:23 UTC, etj requested changes
Domanda nella review.

2020-12-10 17:23 UTC, etj commented on src/main/plugin/iso19139.rndt/layout/config-editor.xml
> +          </action>
Perchè questo bottone?
Quel campo dovrebbe sempre essere valorizzato in automatico dall'UFI.

2020-12-11 08:35 UTC, taba90 commented on src/main/plugin/iso19139.rndt/layout/config-editor.xml
> +          </action>
l'ufi popolava il campo automaticamente ma non lo creava se mancava. Ho rimosso il bottone e aggiunto la creazione automatica nell'ufi

2020-12-14 09:17 UTC, etj commented on src/main/plugin/iso19139.rndt/update-fixed-info.xsl
> +  </xsl:template>
Per aggiungere un elemento si deve:
<xsl:apply-templates select="TUTTI GLI ELEMENTI PRIMA DEL NODO DA AGGIUNGERE"/>
<ELEMENTO DA AGGIUNGERE>
<xsl:apply-templates select="TUTTI GLI ELEMENTI DOPO IL NODO DA AGGIUNGERE"/>

Il codice corrente copia tutto, compresi citedResponsibleParty, series, etc etc, che sono elementi che vanno DOPO gmd:identifier

2020-12-14 09:18 UTC, etj requested changes
Correggere l'aggiunta dell'elmento in UFI come da commento

2020-12-15 12:29 UTC, merged