Revisione schermata editing fix vari
geosolutions-it/iso19139.rndt pull request #26
Opened 2020-10-06 12:10 UTC by taba90

Provides several fixes to rndt metadata editor.

2020-10-07 15:20 UTC, etj requested changes
Per la #24 mancano le modifiche a tutti i template:

https://github.com/geosolutions-it/iso19139.rndt/blob/rndt2/src/main/plugin/iso19139.rndt/templates/iso-19139.rndt-template-vector.xml#L68-L73

2020-10-07 15:20 UTC, etj commented on src/main/plugin/iso19139.rndt/loc/ita/labels.xml
> +      <option value="Francese" >fre</option>
value e label sembrano invertiti

2020-10-07 15:20 UTC, etj commented on src/main/plugin/iso19139.rndt/present/csw/csw-full.xsl
>              <xsl:when test="$isTile">
Rimuovere tutta la gestione dei Tile

2020-10-07 15:20 UTC, etj commented on src/main/plugin/iso19139.rndt/loc/ita/codelists.xml
> +  </codelist>
Non mi sembra corrispondano :)

https://ies-svn.jrc.ec.europa.eu/attachments/download/2469/eReporting_PriorityDataList_V2.0.pdf

2020-10-13 09:35 UTC, taba90 commented on src/main/plugin/iso19139.rndt/present/csw/csw-full.xsl
>              <xsl:when test="$isTile">
fixed

2020-10-13 09:35 UTC, taba90 commented on src/main/plugin/iso19139.rndt/loc/ita/codelists.xml
> +  </codelist>
fixed

2020-10-13 09:35 UTC, taba90 commented on src/main/plugin/iso19139.rndt/loc/ita/labels.xml
> +      <option value="Francese" >fre</option>
fixed

2020-10-23 10:56 UTC, merged